version: "3"
services: 
  meu-postgresql:
    image: bitname/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=apisolid